// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20240203202305_SoftwareTech")]
    partial class SoftwareTech
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.PLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("Domain.Entities.SoftwareTech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("PLanguageId")
                        .HasColumnType("int")
                        .HasColumnName("PLanguageId");

                    b.HasKey("Id");

                    b.HasIndex("PLanguageId");

                    b.ToTable("SoftwareTechs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Asp.Net",
                            PLanguageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spring",
                            PLanguageId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.SoftwareTech", b =>
                {
                    b.HasOne("Domain.Entities.PLanguage", "PLanguage")
                        .WithMany("SoftwareTeches")
                        .HasForeignKey("PLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PLanguage");
                });

            modelBuilder.Entity("Domain.Entities.PLanguage", b =>
                {
                    b.Navigation("SoftwareTeches");
                });
#pragma warning restore 612, 618
        }
    }
}
